name: dock-refine
channels:
  - conda-forge
  - https://levinthal:paradox@conda.graylab.jhu.edu
  - defaults
dependencies:
  - biopython=1.85
  - freesasa=2.2.1
  - numpy=2.0.2
  - pandas=2.2.3
  - python=3.9.21
  - pip:
      - colorama==0.4.6
      - dockq==2.1.3
      - networkx==3.2.1
      - tqdm==4.67.1
